---
title: "ASSIGNMENT 10.2.2"
author: "Kiran Komati"
date: '2021-05-22'
output:
    pdf_document: default
---
    
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = 'C:/Users/kiran/dsc520')
```

# Load the Data

```{r echo=TRUE}
bcd<-read.csv('data/binary-classifier-data.csv')
```
# a) Fit a logistic regression model to the binary-classifier-data.csv dataset

```{r echo=TRUE}
bcd_glm<-glm(formula=label ~ x + y,family = binomial(), data = bcd)
summary(bcd_glm)
```

# b) The dataset (found in binary-classifier-data.csv) contains three variables; label, x, and y. The label variable is either 0 or 1 and is the output we want to predict using the x and y variables.
## i) What is the accuracy of the logistic regression classifier?

```{r echo=TRUE}
bcd$predicted.probabilities<-fitted(bcd_glm)
res <- predict(bcd_glm,type="response")
confMatrix <- table(Actual_Value=bcd$label,Predicted_Value=res>0.5)
confMatrix
(confMatrix[[1,1]] + confMatrix[[2,2]])/sum(confMatrix)
```